version: '3.8'

services:
  client-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_app
    environment:
      - CONFIG_PATH=/root/config/client_config.yaml
    volumes:
      - ./config:/root/config  # 挂载本地 config 目录到容器内的 /root/config 目录
      - ./logs:/root/logs  # 挂载本地 logs 目录到容器内的 /root/logs 目录
    command: ["./client-app"]



  rabbitmq:
    image: rabbitmq:3-management
    container_name: client_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
