app:
  name: "MyProject"
  version: "1.0.0"

database:
  mysql:
    host: "localhost"
    port: 3306
    user: "user"
    password: "password"
    dbname: "my_database"

  clickhouse:
    host: "localhost"
    port: 9000
