version: '3.8'

services:
  app:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./client:/client
      - ./server:/server
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    working_dir: /app
    entrypoint: >
      sh -c "
      if [ \"$PROJECT_NAME\" = \"client\" ]; then
        docker-compose -f /client/docker-compose.yml up;
      elif [ \"$PROJECT_NAME\" = \"server\" ]; then
        docker-compose -f /server/docker-compose.yml up;
      fi
      "
