mysql:
  user: "root"              # MySQL 用户名
  password: "password"      # MySQL 密码
  host: "localhost"         # MySQL 主机地址
  port: 3306                # MySQL 端口
  database: "my_database"   # MySQL 数据库名称

clickhouse:
  host: "localhost"         # ClickHouse 主机地址
  port: 9000                # ClickHouse 端口

log_file: "logs/server.log"

