version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: server_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: server_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  prometheus:
    image: prom/prometheus:latest
    container_name: server_prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./config:/root/config  # 挂载整个配置文件夹到/root/config
      # Prometheus 配置文件在容器内的路径将是 /root/config/prometheus.yml
      - /root/logs:/root/logs # 挂载日志目录

  grafana:
    image: grafana/grafana:latest
    container_name: server_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:3-management
    container_name: server_rabbitmq
    ports:
      - "5673:5672"  # 将 5672 改为其他未占用的端口
      - "15673:15672"  # 将 15672 改为其他未占用的端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pushgateway:
    image: prom/pushgateway:latest
    container_name: server_pushgateway
    ports:
      - "9091:9091"

volumes:
  clickhouse_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  db_data:
